# Generated by Django 6.0.2 on 2026-02-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='tags',
            new_name='tag',
        ),
    ]
