# Generated by Django 6.0.2 on 2026-02-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_tags_document_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='surveys', to='core.document')),
            ],
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
    ]
