# Generated by Django 6.0.2 on 2026-02-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_relatedsurvey_delete_survey_alter_tag_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedSurvey',
            new_name='Survey',
        ),
    ]
