# Generated by Django 6.0.2 on 2026-02-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_relatedsurvey_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='answer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
