# Generated by Django 6.0.2 on 2026-02-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_survey_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
